#ifndef SOURCE_COMPILER_PARSER_NODE_HPP
#define SOURCE_COMPILER_PARSER_NODE_HPP

enum class SyntaxNodeType
{
    SYNTAX_NODE_TYPE_NULL,

    SYNTAX_NODE_TYPE_ROOT,

    SYNTAX_NODE_TYPE_EXPRESSION,
    SYNTAX_NODE_TYPE_TERM,
    SYNTAX_NODE_TYPE_FACTOR,
    SYNTAX_NODE_TYPE_MAGNITUDE,
    SYNTAX_NODE_TYPE_UNARY,
    SYNTAX_NODE_TYPE_PRIMARY

};

class SyntaxNodeVisitor;
struct SyntaxNode
{
    
};

#endif